### ISSUE TITLE
PhantomJS Required?

### ISSUE THREAD

**Issue by BradTotaro** [maruthven/megbot#3]
selenium.common.exceptions.WebDriverException: Message: Unable to start phantomjs with ghostdriver: [Errno 2] No such file or directory

add phantom js to requirements or change driver? 
phantom js has to be built on linux as there isn't an executable installer or package.

**Comment by rubinovitz** [comment]
This is in the installation instructions and has two Mac package examples,
plus the link to the official download page.

**Comment by maruthven** [comment]
You can now install PhantomJS on ubuntu https://gist.github.com/julionc/7476620
